branches:
  only:
    - master

language: cpp

script-anchors:
  - &script-macOS
    - cd $TRAVIS_BUILD_DIR
    - mkdir build
    - cd build
    # RELEASE BUILD
    - cmake .. -DCMAKE_BUILD_TYPE:STRING=Release
    - cmake --build . -- -j2
    # CLEAN
    - rm -rf *
    # DEBUG BUILD
    - cmake .. -DCMAKE_BUILD_TYPE:STRING=Debug
    - cmake --build . -- -j2

matrix:
  include:
    - os: osx
      osx_image: xcode10.1
      script: *script-macOS
