# glfw
set(GLFW_BUILD_EXAMPLES OFF CACHE STRING "" FORCE)
set(GLFW_BUILD_TESTS    OFF CACHE STRING "" FORCE)
set(GLFW_INSTALL        OFF CACHE STRING "" FORCE)

# glew
set(glew-cmake_BUILD_SHARED OFF CACHE STRING "" FORCE)

# glm
set(GLM_TEST_ENABLE OFF CACHE STRING "" FORCE)